### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Kenmmm** [un-pany/flutter-template-plus#1]
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: �����Ԫ�� (uri:"", local:"base-extension")������Ԫ��Ϊ<{}codename>,<{}layoutlib>,<{}api-level>
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
lib/provider/theme_provider.dart:21:31: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      return SchedulerBinding.instance?.window.platformBrightness ==
                              ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:64:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.schedulerPhase ==
                       ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:101:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:112:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:35:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance?.schedulerPhase ==
                         ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:37:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Android/flutter_windows_3.0.0-stable/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.1/lib/src/structs.g.dart:554:31: Error: Member not found: 'UnicodeChar'.
  int get UnicodeChar => Char.UnicodeChar;
                              ^^^^^^^^^^^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.1/lib/src/structs.g.dart:555:38: Error: Setter not found: 'UnicodeChar'.
  set UnicodeChar(int value) => Char.UnicodeChar = value;
                                     ^^^^^^^^^^^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.1/lib/src/structs.g.dart:557:29: Error: Member not found: 'AsciiChar'.
  int get AsciiChar => Char.AsciiChar;
                            ^^^^^^^^^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.1/lib/src/structs.g.dart:558:36: Error: Setter not found: 'AsciiChar'.
  set AsciiChar(int value) => Char.AsciiChar = value;
                                   ^^^^^^^^^
/D:/Android/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Android\flutter_windows_3.0.0-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Android\flutter_windows_3.0.0-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pany-ang** [comment]
环境是否和我的一样？

**Comment by InTheClodus** [comment]
他这个项目没有支持flutter3.0

**Comment by pany-ang** [comment]
> 他这个项目没有支持flutter3.0

最近都搞 Vue3 的仓库去了，等后面看有空了，我升级一下这个仓库吧。或者你们自己升级一下，应该也不难

**Comment by InTheClodus** [comment]
> > 他这个项目没有支持flutter3.0
> 
> 最近都搞 Vue3 的仓库去了，等后面看有空了，我升级一下这个仓库吧。或者你们自己升级一下，应该也不难

哈哈，还好啦，升级不难，我就是看个思路的
